# Generated by Django 5.2.7 on 2025-10-23 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('rg', models.CharField(blank=True, max_length=14, null=True)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'CPF deve conter 11 dígitos numéricos.')])),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Telefone deve ter 10 ou 11 dígitos (DDD + número).')])),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Telefone deve ter 10 ou 11 dígitos (DDD + número).')])),
                ('cep', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{8}$', 'CEP deve conter 8 dígitos numéricos.')])),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(blank=True, max_length=30, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
    ]
