# Generated by Django 5.2.7 on 2025-11-03 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaVendas', '0003_funcionariomodel_alter_clientemodel_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=8, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=30, null=True)),
                ('cidade', models.CharField(blank=True, max_length=30, null=True)),
                ('uf', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True)),
                ('contato_responsavel', models.CharField(blank=True, max_length=60, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno do produto', max_length=50, unique=True)),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras (EAN)', max_length=50, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('ALIMENTO', 'Alimentos'), ('BEBIDA', 'Bebidas'), ('HIGIENE', 'Higiene e Limpeza'), ('ELETRONICO', 'Eletrônicos'), ('VESTUARIO', 'Vestuário'), ('MOVEL', 'Móveis'), ('FERRAMENTA', 'Ferramentas'), ('MATERIAL', 'Material de Construção'), ('PAPELARIA', 'Papelaria'), ('OUTROS', 'Outros')], default='OUTROS', max_length=20)),
                ('unidade_medida', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('PC', 'Peça'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro'), ('M', 'Metro'), ('CM', 'Centímetro'), ('M2', 'Metro Quadrado'), ('M3', 'Metro Cúbico'), ('DZ', 'Dúzia'), ('PCT', 'Pacote'), ('FD', 'Fardo')], default='UN', max_length=5)),
                ('estoque_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estoque_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('margem_lucro', models.DecimalField(blank=True, decimal_places=2, help_text='Margem de lucro em %', max_digits=5, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='sistemaVendas.fornecedormodel')),
            ],
        ),
    ]
