# Generated by Django 5.2.7 on 2025-11-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaVendas', '0005_vendamodel_itemvendamodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendamodel',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('CARTAO_CREDITO', 'Cartão de Crédito'), ('CARTAO_DEBITO', 'Cartão de Débito'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência Bancária'), ('CHEQUE', 'Cheque'), ('CREDIARIO', 'Crediário')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vendamodel',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=15),
        ),
    ]
