# Generated by Django 5.2.7 on 2025-11-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaVendas', '0006_alter_vendamodel_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemodel',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
