# Generated by Django 5.2.7 on 2025-11-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaVendas', '0007_clientemodel_ativo_alter_clientemodel_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedormodel',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='funcionariomodel',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
